# Generated by Django 3.2.4 on 2021-06-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210625_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conent',
            new_name='Content',
        ),
    ]
