# Generated by Django 3.2.4 on 2021-06-26 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210626_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
