# Generated by Django 3.2.4 on 2021-06-26 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_todolist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.todolist')),
            ],
        ),
    ]
